drop table if exists friends, users, films, likes, genres, mpa, films_genres;

CREATE TABLE if not exists users (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(100) NOT NULL,
        email varchar(100) NOT NULL UNIQUE,
        login varchar(100) NOT NULL UNIQUE,
        birthday date
);

CREATE TABLE if not exists genres (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE if not exists mpa (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(7) NOT NULL UNIQUE
);

CREATE TABLE if not exists films (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(100) NOT NULL UNIQUE,
        description varchar(200) NOT NULL,
        duration integer NOT NULL,
        mpa_id integer references mpa(id) on delete cascade,
        release_date date
);

CREATE TABLE if not exists likes (
        film_id integer NOT NULL references films(id) on delete cascade,
        user_id integer NOT NULL references users(id) on delete cascade,
        PRIMARY KEY (film_id, user_id)
);

CREATE TABLE if not exists friends (
        user_id integer NOT NULL references users(id) on delete cascade,
        friend_id integer NOT NULL references users(id) on delete cascade,
        confirm boolean,
        PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE if not exists films_genres (
        film_id integer NOT NULL references films(id) on delete cascade,
        genre_id integer NOT NULL references genres(id) on delete cascade,
        PRIMARY KEY (film_id, genre_id)
);