drop table if exists friends, users, films, likes, genres, raitings;

CREATE TABLE if not exists users (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(150) NOT NULL,
        email varchar(150) NOT NULL UNIQUE,
        login varchar(150) NOT NULL UNIQUE,
        birthday date
);

CREATE TABLE if not exists genres (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE if not exists raitings (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(7) NOT NULL UNIQUE
);

CREATE TABLE if not exists films (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(150) NOT NULL UNIQUE,
        description varchar(1000) NOT NULL,
        duration long,
        raiting_id integer NOT NULL references raitings(id) on delete cascade,
        genre_id integer NOT NULL references genres(id) on delete cascade,
        likes integer,
        release_date date
);

CREATE TABLE if not exists likes (
        film_id integer NOT NULL references films(id) on delete cascade,
        user_id integer NOT NULL references users(id) on delete cascade
);

CREATE TABLE if not exists friends (
        user_id integer NOT NULL references users(id) on delete cascade,
        friend_id integer NOT NULL references users(id) on delete cascade,
        confirm boolean
);
